In [ ]:
a = 20
print(a)


20


In [2]:
 # pandas library
# pandas datafrane is two daimentional data structure with labeled axes (rows and columns)

In [1]:
import pandas as pd

In [4]:
#creating a pandas dataframe
from sklearn.datasets import load_iris
iris = load_iris()

In [5]:
type(iris)

sklearn.utils._bunch.Bunch

In [9]:
print(iris.data)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [10]:
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [11]:
print(iris)


{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [12]:
iris_df.head()  # Display the first few rows of the DataFrame

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [16]:
iris_df.shape

(150, 4)

In [19]:
#importing the data from csv into the pandas dataframe
iris_df = pd.read_csv('iris')

FileNotFoundError: [Errno 2] No such file or directory: 'iris'

In [3]:
#creating a dataframe with random values
import numpy as np
random_df = pd.DataFrame(np.random.rand(5, 3))

In [4]:
random_df.head()  # Display the first few rows of the random DataFrame

0         1         2
0  0.721034  0.029422  0.931345
1  0.041301  0.604446  0.845753
2  0.664857  0.826769  0.835386
3  0.868548  0.736710  0.753662
4  0.664107  0.594813  0.702656

In [6]:
 random_df.describe()  # Get a statistical summary of the random DataFrame

0         1         2
count  5.000000  5.000000  5.000000
mean   0.591969  0.558432  0.813760
std    0.318946  0.311079  0.088421
min    0.041301  0.029422  0.702656
25%    0.664107  0.594813  0.753662
50%    0.664857  0.604446  0.835386
75%    0.721034  0.736710  0.845753
max    0.868548  0.826769  0.931345

In [ ]:
#shape is tell the daimention of the dataframe
random_df.shape

(5, 3)

In [11]:
#find the number of the row and columns
random_df.tail()  # Display the last few rows of the DataFrame

0         1         2
0  0.721034  0.029422  0.931345
1  0.041301  0.604446  0.845753
2  0.664857  0.826769  0.835386
3  0.868548  0.736710  0.753662
4  0.664107  0.594813  0.702656

In [12]:
#information about the dataframe
random_df.info()  # Get a concise summary of the DataFrame


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       5 non-null      float64
 1   1       5 non-null      float64
 2   2       5 non-null      float64
dtypes: float64(3)
memory usage: 252.0 bytes


In [15]:
#find the missing values in the dataframe
missing_values = random_df.isnull().sum()

In [17]:
print(missing_values)  # Display the count of missing values in each column

0    0
1    0
2    0
dtype: int64
